apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::808953420819:role/eksctl-demo-cluster-1-cluster-ServiceRole-R9QABQ7BR7MC
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::808953420819:role/service-role/codebuild-ecrconnection-service-role
      username: build
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::808953420819:user/Tanmay
      username: Tanmay
      groups:
        - system:masters



kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system